# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SEVurity
email: 
description: >- # this means to ignore newlines until "baseurl:"
  SEVurity is a research paper, showing how to exploit flaws in AMD's SEV-ES technology to execute arbitrary Code in SEV-ES protected VMs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed




#My Customizations
has_logo: false
paper_logo: test-logo-2.png

has_paper_link: true
#Just the name of the file
paper_link: SEVurity-paper.pdf
has_slide_link: true
#Just the name of the file
slide_link: SEVurity-slides.pdf


#dirty fix: on github the link to css file must be preended with /repo-name. For local we don't find the file with this prefix
#chose between "local" and "github"
deployment: github

github:
  #Link for the "view it on github button"
  repository_url: https://github.com/UzL-ITS/SEVurity
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
